# Generated by Django 4.0.1 on 2022-05-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
