# Generated by Django 4.0.1 on 2022-05-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
