# Generated by Django 4.0.1 on 2022-05-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_post_author_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
