# Generated by Django 4.0.1 on 2022-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_post_author_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
